add prerender bot
JayBizzle/Crawler-Detect pull request #441
Opened 2021-03-02 11:16 UTC by LinusGeffarth

Not sure this is how it's supposed to be done, but I tried 😄

2021-03-02 11:19 UTC, LinusGeffarth commented
Apparently this really isn't how to. @JayBizzle can you assist?

2021-03-02 11:24 UTC, JayBizzle requested changes

2021-03-02 11:24 UTC, JayBizzle commented on src/Fixtures/Crawlers.php
> +        'Prerender'
You missed a comma here

2021-03-02 11:44 UTC, LinusGeffarth commented on src/Fixtures/Crawlers.php
> +        'Prerender'
argh – fixed that

2021-03-03 20:54 UTC, JayBizzle approved these changes

2021-03-03 20:54 UTC, merged

2021-03-03 20:54 UTC, JayBizzle commented
Thanks!